//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guider
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelplace
    {
        public int id { get; set; }
        public string travelplace1 { get; set; }
        public string location { get; set; }
        public string division { get; set; }
        public string description { get; set; }
        public string travelguidermail { get; set; }
        public string pictures { get; set; }
        public string status { get; set; }
    }
}
